# Generated by Django 3.1.14 on 2021-12-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='directionsForRecipe',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='card',
            name='ingredientsForRecipe',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
