# Generated by Django 3.1.14 on 2021-12-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20211213_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='directionsForRecipe',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
