# Generated by Django 3.1.14 on 2021-12-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20211213_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='jumbotronImage',
            field=models.ImageField(null=True, upload_to='articles/images/'),
        ),
    ]
